name: Update
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  build-content:
    name: create-content
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Show Log Loaded
        run: |
          pushd libs/airwindows
          git log plugins/MacVST/Galactic/source/GalacticProc.cpp
          popd
      - name: Do Update
        run: . ./scripts/updateToLatest.sh
      - name: Commit code 
        run: |
          git config --global user.name 'GithubActions BaconPaul Bot'
          git config --global user.email 'baconpaul@users.noreply.github.com'
          git add .
          git commit -m "Update to Latest Airwin"
          git push
